### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] 

### ISSUE THREAD

**Issue by ajsb85** [angular/mobile-toolkit#29]
Build error

The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:

```
Error: EPERM: operation not permitted, symlink '<path>\hello-mobile\tmp\broccoli_type_script_compiler-cache_path-FFrpJN1M.tmp\src\app\environment.js.map' -> '<path>\hello-mobile\tmp\broccoli_type_script_compiler-output_path-jdW6uW78.tmp\src\app\environment.js.map'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1048:18)
    at BroccoliTypeScriptCompiler._outputFile (<path>\hello-mobile\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:206:8)
    at output.outputFiles.forEach.o (<path>\hello-mobile\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:108:18)
    at Array.forEach (native)
    at pathsToEmit.forEach.tsFilePath (<path>\hello-mobile\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:107:30)
    at Array.forEach (native)
    at BroccoliTypeScriptCompiler._doIncrementalBuild (<path>\hello-mobile\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:93:19)
    at BroccoliTypeScriptCompiler.build (<path>\hello-mobile\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at <path>\hello-mobile\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (<path>\hello-mobile\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (<path>\hello-mobile\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (<path>\hello-mobile\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (<path>\hello-mobile\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (<path>\hello-mobile\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (<path>\hello-mobile\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (<path>\hello-mobile\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (<path>\hello-mobile\node_modules\angular-cli\lib\broccoli\angular2-app.js:280:18)
    at Angular2App._buildTree (<path>\hello-mobile\node_modules\angular-cli\lib\broccoli\angular2-app.js:101:23)
    at new Angular2App (<path>\hello-mobile\node_modules\angular-cli\lib\broccoli\angular2-app.js:42:23)
    at module.exports (<path>\hello-mobile\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (<path>\hello-mobile\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (<path>\hello-mobile\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:89:10)
    at new Class (<path>\hello-mobile\node_modules\angular-cli\node_modules\ember-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (<path>\hello-mobile\node_modules\angular-cli\node_modules\ember-cli\lib\tasks\serve.js:15:19)
    at <path>\hello-mobile\node_modules\angular-cli\node_modules\ember-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (<path>\hello-mobile\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (<path>\hello-mobile\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (<path>\hello-mobile\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (<path>\hello-mobile\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
```

OS: **Windows 7 64bit**

**Comment by ajsb85** [comment]
Works as administrator

**Comment by SwagMuffinMcYoloPants** [comment]
Isn't this more of a problem with Angular CLI?  I've seen this issue before on their issues page.

#https://github.com/angular/angular-cli/issues/641

**Comment by rathahin** [comment]
In windows start command line as Administrator, the error solve. Thanks ajsb85
