### ISSUE TITLE
The Broccoli Plugin: [SourceMapConcat] failed 

### ISSUE THREAD

**Issue by BhaskaranR** [angular/mobile-toolkit#37]
ng build --prod fails with this error

The Broccoli Plugin: [SourceMapConcat] failed with:
Error: ENOENT: no such file or directory, open 'C:\hello-mobile\tmp\source_map_concat-input_base_path-HobpJYRu.tmp\0\vendor\reflect-metadata\Reflect.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at SourceMap.<anonymous> (C:\hello-mobile\node_modules\angular-cli\node_modules\broccoli-concat\node_modules\fast-sourcemap-concat\lib\source-map.js:282:29)

**Comment by michalstepien** [comment]
I have the same error

**Comment by Tusabras** [comment]
for me.. i can compile it... but after that i have this error:

app-concat.js:7 Uncaught ReferenceError: require is not defined
