### ISSUE TITLE
The Broccoli Plugin: [AppShellPlugin] failed: file does not exist.  Does it support templateUrl?

### ISSUE THREAD

**Issue by dcunited08** [angular/mobile-toolkit#38]
It appears the templateUrl is not supported by default.

```
The Broccoli Plugin: [AppShellPlugin] failed with:
Error: Command failed: node /Users/dcook/workspace/fireblog/node_modules/angular2-broccoli-prerender/dist/child_proc.js  --sourceHtml=/Users/dcook/workspace/fireblog/tmp/app_shell_plugin-input_base_path-GBe5b7f4.tmp/0/index.html --optionsPath=/Users/dcook/workspace/fireblog/tmp/app_shell_plugin-input_base_path-GBe5b7f4.tmp/0/main-app-shell --outputIndexPath=/Users/dcook/workspace/fireblog/tmp/app_shell_plugin-output_path-WRHSwL3M.tmp/index.html
EXCEPTION: Failed to load /Users/dcook/workspace/fireblog/tmp/broccoli_type_script_compiler-cache_path-o7NyPkVK.tmp/src/app/fireblog.component.html
Failed to load /Users/dcook/workspace/fireblog/tmp/broccoli_type_script_compiler-cache_path-o7NyPkVK.tmp/src/app/fireblog.component.html

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)

The broccoli plugin was instantiated at:
    at AppShellPlugin.Plugin (/Users/dcook/workspace/fireblog/node_modules/broccoli-plugin/index.js:10:31)
    at AppShellPlugin.CachingWriter [as constructor] (/Users/dcook/workspace/fireblog/node_modules/broccoli-caching-writer/index.js:21:10)
    at new AppShellPlugin (/Users/dcook/workspace/fireblog/node_modules/angular2-broccoli-prerender/dist/prerender.js:15:16)
    at Angular2App._buildTree (/Users/dcook/workspace/fireblog/node_modules/angular-cli/lib/broccoli/angular2-app.js:153:48)
    at new Angular2App (/Users/dcook/workspace/fireblog/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/dcook/workspace/fireblog/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/dcook/workspace/fireblog/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/dcook/workspace/fireblog/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/dcook/workspace/fireblog/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/dcook/workspace/fireblog/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/dcook/workspace/fireblog/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/dcook/workspace/fireblog/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/dcook/workspace/fireblog/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/dcook/workspace/fireblog/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/dcook/workspace/fireblog/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

```

**Comment by mmgyce** [comment]
look this https://github.com/angular/angular-cli/issues/810
