### ISSUE TITLE
ng serve for hello-mobile ... breaks 

### ISSUE THREAD

**Issue by muthuveerappan** [angular/mobile-toolkit#39]
I installed angular-cli but not able to get this version - 1.0.0-beta.4 ....

- npm install -g angular-cli

This installs the latest version 1.0.0-beta.5 with this i am not able to get the project working ., 

ng serve errors out as below ., 

D:\nodejs>cd hello-mobile

D:\nodejs\hello-mobile>ng serve
Livereload server on http://localhost:49155
Serving on http://localhost:4200/
The Broccoli Plugin: [AppShellPlugin] failed with:
Error: Command failed: C:\windows\system32\cmd.exe /s /c "node D:\nodejs\hello-mobile\node_modules\angular2-broccoli-prerender\dist\child_proc.js  --sourceHtml=D:\no
dejs\hello-mobile\tmp\app_shell_plugin-input_base_path-vbnkT0hw.tmp\0\index.html --optionsPath=D:\nodejs\hello-mobile\tmp\app_shell_plugin-input_base_path-vbnkT0hw.t
mp\0\main-app-shell --outputIndexPath=D:\nodejs\hello-mobile\tmp\app_shell_plugin-output_path-AQgaL2Dn.tmp\index.html"

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

The broccoli plugin was instantiated at:
    at AppShellPlugin.Plugin (D:\nodejs\hello-mobile\node_modules\angular2-broccoli-prerender\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index
.js:10:31)
    at AppShellPlugin.CachingWriter [as constructor] (D:\nodejs\hello-mobile\node_modules\angular2-broccoli-prerender\node_modules\broccoli-caching-writer\index.js:2
1:10)
    at new AppShellPlugin (D:\nodejs\hello-mobile\node_modules\angular2-broccoli-prerender\dist\prerender.js:15:16)
    at Angular2App._buildTree (D:\nodejs\hello-mobile\node_modules\angular-cli\lib\broccoli\angular2-app.js:153:48)
    at new Angular2App (D:\nodejs\hello-mobile\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (D:\nodejs\hello-mobile\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\nodejs\hello-mobile\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\nodejs\hello-mobile\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (D:\nodejs\hello-mobile\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\nodejs\hello-mobile\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)
    at D:\nodejs\hello-mobile\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (D:\nodejs\hello-mobile\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\nodejs\hello-mobile\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\nodejs\hello-mobile\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\nodejs\hello-mobile\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)

How can i get old version of angular-cli or how can i fix this error .... 

Any help is much appreciated. 

Regards.,
Muthuveerappan

**Comment by muthuveerappan** [comment]
I run as administrator ., 

When i did - npm install -g angular-cli - i got the below warnings...


npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use
 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!

**Comment by muthuveerappan** [comment]
which version i should use  '1.0.0-beta.4', or  '1.0.0-beta.2-mobile.4'   ?

**Comment by Splaktar** [comment]
The deprecated warnings shouldn't be a major problem. 

To play with the mobile-toolkit, you will probably want the latest master since it includes some important fixes:

```
npm install -g git://github.com/angular/angular-cli.git#4108a674b46ccf94b07984c7aed3252e55615bde
```

**Comment by muthuveerappan** [comment]
Thanks., will give it a try .,

**Comment by ystreibel** [comment]
Hi,

I have the same problem : 

```
$ ng serve
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/ykaribou/Projects/mobile-toolkit/hello-mobile/tmp/broccoli_type_script_compiler-input_base_path-RgGUJAwR.tmp/0/src/app/hello-mobile.component.ts (7, 13): Cannot find name 'module'.
  /Users/ykaribou/Projects/mobile-toolkit/hello-mobile/tmp/broccoli_type_script_compiler-input_base_path-RgGUJAwR.tmp/0/src/typings.d.ts (1, 1): File '/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/tmp/broccoli_type_script_compiler-input_base_path-RgGUJAwR.tmp/0/typings/index.d.ts' not found.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/lib/broccoli/angular2-app.js:329:18)
    at Angular2App._buildTree (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/lib/broccoli/angular2-app.js:124:23)
    at new Angular2App (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/ykaribou/Projects/mobile-toolkit/hello-mobile/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```
