### ISSUE TITLE
requestAnimationFrame is not defined after including the md-spinner

### ISSUE THREAD

**Issue by msaelices** [angular/mobile-toolkit#53]
Following [Sharing the Root Component](https://github.com/angular/mobile-toolkit/blob/master/guides/app-shell.md#sharing-the-root-component), after doing `ng serve` and pointing the browser to http://localhost:4200/hello this is the traceback I get:

`Error: Command failed: /bin/sh -c node /home/msaelices/src/hello-mobile/node_modules/angular2-broccoli-prerender/dist/child_proc.js  --sourceHtml=/home/msaelices/src/hello-mobile/tmp/app_shell_plugin-input_base_path-AnDBdsfB.tmp/0/index.html --optionsPath=/home/msaelices/src/hello-mobile/tmp/app_shell_plugin-input_base_path-AnDBdsfB.tmp/0/main-app-shell --outputIndexPath=/home/msaelices/src/hello-mobile/tmp/app_shell_plugin-output_path-si91VoBm.tmp/index.html
EXCEPTION: Error in package:/home/msaelices/src/hello-mobile/tmp/broccoli_type_script_compiler-cache_path-wQpEd0nk.tmp/src/app/hello-mobile.component.js class HelloMobileAppComponent - inline template:4:2
ORIGINAL EXCEPTION: ReferenceError: requestAnimationFrame is not defined
ORIGINAL STACKTRACE:
ReferenceError: requestAnimationFrame is not defined
    at MdSpinner.MdProgressCircle._animateCircle (/home/msaelices/src/hello-mobile/node_modules/@angular2-material/progress-circle/progress-circle.js:123:13)
    at animate (/home/msaelices/src/hello-mobile/node_modules/@angular2-material/progress-circle/progress-circle.js:136:19)
    at MdSpinner.MdProgressCircle._startIndeterminateAnimation (/home/msaelices/src/hello-mobile/node_modules/@angular2-material/progress-circle/progress-circle.js:145:13)
    at MdSpinner.Object.defineProperty.set [as mode] (/home/msaelices/src/hello-mobile/node_modules/@angular2-material/progress-circle/progress-circle.js:84:22)
    at new MdSpinner (/home/msaelices/src/hello-mobile/node_modules/@angular2-material/progress-circle/progress-circle.js:195:19)
    at DebugAppView._View_HelloMobileAppComponent1.createInternal (HelloMobileAppComponent.template.js:90:25)
    at DebugAppView.AppView.create (/home/msaelices/src/hello-mobile/node_modules/@angular/core/src/linker/view.js:66:21)
    at DebugAppView.create (/home/msaelices/src/hello-mobile/node_modules/@angular/core/src/linker/view.js:259:44)
    at TemplateRef_.createEmbeddedView (/home/msaelices/src/hello-mobile/node_modules/@angular/core/src/linker/template_ref.js:56:14)
    at ViewContainerRef_.createEmbeddedView (/home/msaelices/src/hello-mobile/node_modules/@angular/core/src/linker/view_container_ref.js:98:35)`

**Comment by Splaktar** [comment]
This is a known issue with material2: https://github.com/angular/material2/issues/459
