### ISSUE TITLE
ng new $PROJECT_NAME --mobile fails

### ISSUE THREAD

**Issue by adamduren** [angular/mobile-toolkit#75]
Not sure what's going on here but I've never been able to get angular-cli mobile to work. In this case it looks like two different versions of angular-universal are required and two different versions of angular core are required... Any suggestions?
```
$ npm install

> bpm2@0.0.0 postinstall C:\Users\adamd\workspace\bpm2
> typings install


├── es6-shim (ambient)
├── node (ambient)
├── angular-protractor (ambient dev)
├── jasmine (ambient dev)
└── selenium-webdriver (ambient dev)

balanced-match@0.4.1 node_modules\angular-cli\node_modules\ember-cli\node_modules\tree-sync\node_modules\walk-sync\node_modules\matcher-collection\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-match -> node_modules\balanced-match
concat-map@0.0.1 node_modules\angular-cli\node_modules\ember-cli\node_modules\tree-sync\node_modules\walk-sync\node_modules\matcher-collection\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map -> node_modules\concat-map
brace-expansion@1.1.5 node_modules\angular-cli\node_modules\ember-cli\node_modules\tree-sync\node_modules\walk-sync\node_modules\matcher-collection\node_modules\minimatch\node_modules\brace-expansion -> node_modules\brace-expansion
minimatch@3.0.2 node_modules\angular-cli\node_modules\ember-cli\node_modules\tree-sync\node_modules\walk-sync\node_modules\matcher-collection\node_modules\minimatch -> node_modules\minimatch
matcher-collection@1.0.2 node_modules\angular-cli\node_modules\ember-cli\node_modules\tree-sync\node_modules\walk-sync\node_modules\matcher-collection -> node_modules\matcher-collection
object-assign@4.1.0 node_modules\angular-cli\node_modules\ember-cli\node_modules\inquirer\node_modules\figures\node_modules\object-assign -> node_modules\object-assign
walk-sync@0.2.6 node_modules\angular-cli\node_modules\ember-cli\node_modules\tree-sync\node_modules\walk-sync -> node_modules\walk-sync
bpm2@0.0.0 C:\Users\adamd\workspace\bpm2
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.3
+-- angular-cli@1.0.0-beta.8
| +-- ember-cli@2.5.0
| | +-- exists-sync@0.0.3
| | `-- through@2.3.8
| +-- typescript@1.8.10
| `-- typings@0.8.1
|   +-- any-promise@1.3.0
|   +-- archy@1.0.0
|   +-- bluebird@3.4.1
|   +-- columnify@1.5.4
|   | +-- strip-ansi@3.0.1
|   | | `-- ansi-regex@2.0.0
|   | `-- wcwidth@1.0.1
|   |   `-- defaults@1.0.3
|   |     `-- clone@1.0.2
|   +-- listify@1.0.0
|   +-- minimist@1.2.0
|   +-- typings-core@0.3.1
|   | +-- array-uniq@1.0.3
|   | +-- configstore@2.0.0
|   | | +-- dot-prop@2.4.0
|   | | | `-- is-obj@1.0.1
|   | | +-- os-tmpdir@1.0.1
|   | | +-- osenv@0.1.3
|   | | | `-- os-homedir@1.0.1
|   | | +-- uuid@2.0.2
|   | | +-- write-file-atomic@1.1.4
|   | | | +-- imurmurhash@0.1.4
|   | | | `-- slide@1.1.6
|   | | `-- xdg-basedir@2.0.0
|   | |   `-- os-homedir@1.0.1
|   | +-- debug@2.2.0
|   | | `-- ms@0.7.1
|   | +-- detect-indent@4.0.0
|   | | `-- repeating@2.0.1
|   | |   `-- is-finite@1.0.1
|   | |     `-- number-is-nan@1.0.0
|   | +-- graceful-fs@4.1.4
|   | +-- has@1.0.1
|   | | `-- function-bind@1.1.0
|   | +-- invariant@2.2.1
|   | | `-- loose-envify@1.2.0
|   | |   `-- js-tokens@1.0.3
|   | +-- is-absolute@0.2.5
|   | | +-- is-relative@0.2.1
|   | | | `-- is-unc-path@0.1.1
|   | | |   `-- unc-path-regex@0.1.2
|   | | `-- is-windows@0.1.1
|   | +-- lockfile@1.0.1
|   | +-- make-error-cause@1.1.1
|   | | `-- make-error@1.1.1
|   | +-- mkdirp@0.5.1
|   | | `-- minimist@0.0.8
|   | +-- object.pick@1.1.2
|   | | `-- isobject@2.1.0
|   | |   `-- isarray@1.0.0
|   | +-- parse-json@2.2.0
|   | | `-- error-ex@1.3.0
|   | |   `-- is-arrayish@0.2.1
|   | +-- popsicle@5.0.1
|   | | +-- arrify@1.0.1
|   | | +-- concat-stream@1.5.1
|   | | | +-- inherits@2.0.1
|   | | | +-- readable-stream@2.0.6
|   | | | | +-- core-util-is@1.0.2
|   | | | | +-- isarray@1.0.0
|   | | | | +-- process-nextick-args@1.0.7
|   | | | | +-- string_decoder@0.10.31
|   | | | | `-- util-deprecate@1.0.2
|   | | | `-- typedarray@0.0.6
|   | | +-- form-data@0.2.0
|   | | | +-- async@0.9.2
|   | | | +-- combined-stream@0.0.7
|   | | | | `-- delayed-stream@0.0.5
|   | | | `-- mime-types@2.0.14
|   | | |   `-- mime-db@1.12.0
|   | | +-- methods@1.1.2
|   | | `-- tough-cookie@2.2.2
|   | +-- popsicle-proxy-agent@1.0.0
|   | | +-- http-proxy-agent@1.0.0
|   | | | +-- agent-base@2.0.1
|   | | | | `-- semver@5.0.3
|   | | | `-- extend@3.0.0
|   | | `-- https-proxy-agent@1.0.0
|   | |   +-- agent-base@2.0.1
|   | |   | `-- semver@5.0.3
|   | |   `-- extend@3.0.0
|   | +-- popsicle-retry@2.0.0
|   | +-- popsicle-status@1.0.2
|   | +-- promise-finally@2.2.1
|   | +-- rc@1.1.6
|   | | +-- deep-extend@0.4.1
|   | | +-- ini@1.3.4
|   | | `-- strip-json-comments@1.0.4
|   | +-- rimraf@2.5.2
|   | +-- sort-keys@1.1.2
|   | | `-- is-plain-obj@1.1.0
|   | +-- string-template@1.0.0
|   | +-- strip-bom@2.0.0
|   | | `-- is-utf8@0.2.1
|   | +-- thenify@3.2.0
|   | +-- throat@2.0.2
|   | +-- touch@1.0.0
|   | | `-- nopt@1.0.10
|   | |   `-- abbrev@1.0.9
|   | `-- zip-object@0.1.0
|   +-- update-notifier@0.6.3
|   | +-- boxen@0.3.1
|   | | +-- filled-array@1.1.0
|   | | +-- repeating@2.0.1
|   | | | `-- is-finite@1.0.1
|   | | |   `-- number-is-nan@1.0.0
|   | | +-- string-width@1.0.1
|   | | | +-- code-point-at@1.0.0
|   | | | | `-- number-is-nan@1.0.0
|   | | | +-- is-fullwidth-code-point@1.0.0
|   | | | | `-- number-is-nan@1.0.0
|   | | | `-- strip-ansi@3.0.1
|   | | |   `-- ansi-regex@2.0.0
|   | | `-- widest-line@1.0.0
|   | +-- configstore@2.0.0
|   | | +-- dot-prop@2.4.0
|   | | | `-- is-obj@1.0.1
|   | | +-- graceful-fs@4.1.4
|   | | +-- mkdirp@0.5.1
|   | | | `-- minimist@0.0.8
|   | | +-- os-tmpdir@1.0.1
|   | | +-- osenv@0.1.3
|   | | | `-- os-homedir@1.0.1
|   | | +-- uuid@2.0.2
|   | | +-- write-file-atomic@1.1.4
|   | | | +-- imurmurhash@0.1.4
|   | | | `-- slide@1.1.6
|   | | `-- xdg-basedir@2.0.0
|   | |   `-- os-homedir@1.0.1
|   | +-- is-npm@1.0.0
|   | +-- latest-version@2.0.0
|   | | `-- package-json@2.3.2
|   | |   +-- got@5.6.0
|   | |   | +-- create-error-class@3.0.2
|   | |   | | `-- capture-stack-trace@1.0.0
|   | |   | +-- duplexer2@0.1.4
|   | |   | +-- is-plain-obj@1.1.0
|   | |   | +-- is-redirect@1.0.0
|   | |   | +-- is-retry-allowed@1.0.0
|   | |   | +-- is-stream@1.1.0
|   | |   | +-- lowercase-keys@1.0.0
|   | |   | +-- node-status-codes@1.0.0
|   | |   | +-- parse-json@2.2.0
|   | |   | | `-- error-ex@1.3.0
|   | |   | |   `-- is-arrayish@0.2.1
|   | |   | +-- pinkie-promise@2.0.1
|   | |   | | `-- pinkie@2.0.4
|   | |   | +-- read-all-stream@3.1.0
|   | |   | +-- readable-stream@2.1.4
|   | |   | | +-- buffer-shims@1.0.0
|   | |   | | +-- core-util-is@1.0.2
|   | |   | | +-- inherits@2.0.1
|   | |   | | +-- isarray@1.0.0
|   | |   | | +-- process-nextick-args@1.0.7
|   | |   | | +-- string_decoder@0.10.31
|   | |   | | `-- util-deprecate@1.0.2
|   | |   | +-- timed-out@2.0.0
|   | |   | +-- unzip-response@1.0.0
|   | |   | `-- url-parse-lax@1.0.0
|   | |   |   `-- prepend-http@1.0.4
|   | |   +-- rc@1.1.6
|   | |   | +-- deep-extend@0.4.1
|   | |   | +-- ini@1.3.4
|   | |   | `-- strip-json-comments@1.0.4
|   | |   +-- registry-url@3.1.0
|   | |   `-- semver@5.1.0
|   | `-- semver-diff@2.1.0
|   |   `-- semver@5.1.0
|   +-- wordwrap@1.0.0
|   `-- xtend@4.0.1
+-- UNMET PEER DEPENDENCY angular2-universal@0.100.5
| `-- UNMET PEER DEPENDENCY angular2-universal@0.104.1 extraneous
`-- protractor@3.3.0
  `-- request@2.67.0
    `-- http-signature@1.1.1
      `-- sshpk@1.8.3
        +-- ecc-jsbn@0.1.1
        +-- jodid25519@1.0.2
        +-- jsbn@0.1.0
        `-- tweetnacl@0.13.3

npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN @angular/app-shell@0.0.0 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN angular2-express-engine@0.15.0 requires a peer of angular2-universal@^0.104.0 but none was installed.
npm WARN angular2-hapi-engine@0.15.0 requires a peer of angular2-universal@^0.104.0 but none was installed.
npm WARN angular2-express-engine@0.15.0 requires a peer of angular2-universal@^0.104.0 but none was installed.
npm WARN angular2-hapi-engine@0.15.0 requires a peer of angular2-universal@^0.104.0 but none was installed.
```

**Comment by adamduren** [comment]
I should add
```
angular-cli@1.0.0-beta.8
npm@3.10.3
node@6.2.2
```

**Comment by markjritchie** [comment]
Must admit I'm starting to look pretty bad at work here just now since I'm recommending angular 2 mobile for our new web app and I can't even get up and running either by doing

`ng new myApp -- mobile`

with beta9 of the CLI

or if I download the source here and run

`ng serve`

under beta9 I get

Error: Typescript found the following errors:
  D:/EOX2/vlsp/hello-mobile/tmp/broccoli_type_script_compiler-input_base_path-7ko4kLjW.tmp/0/src/app/hello-mobile.compon
ent.ts (7, 13): Cannot find name 'module'.
  D:/EOX2/vlsp/hello-mobile/tmp/broccoli_type_script_compiler-input_base_path-7ko4kLjW.tmp/0/src/typings.d.ts (1, 1): Fi
le 'D:/EOX2/vlsp/hello-mobile/tmp/broccoli_type_script_compiler-input_base_path-7ko4kLjW.tmp/0/typings/index.d.ts' not f
ound.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\lib\broccoli\b
roccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\lib\broccoli\broccoli-typesc
ript.js:43:10)
    at D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1
036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\rsvp\dist\rsv
p.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:10
19:11)
    at lib$rsvp$asap$$flush (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\broccoli-plugi
n\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\nod
e_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\lib\broccoli\broccoli-typescript.j
s:26:49)
    at Angular2App._getTsTree (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\lib\broccoli\angular2-app.js:329:18)
    at Angular2App._buildTree (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (D:\EOX2\vlsp\hello-mobile\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_mo
dules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\angular-cl
i\lib\models\builder.js:89:10)
    at new Class (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\angular-cli
\lib\tasks\serve.js:15:19)
    at D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1
036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\rsvp\dist\rsv
p.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:10
19:11)
    at lib$rsvp$asap$$flush (D:\EOX2\vlsp\hello-mobile\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
