### ISSUE TITLE
'[AppShellPlugin] failed: undefined' when using Pipes

### ISSUE THREAD

**Issue by hdjirdeh** [angular/mobile-toolkit#88]
Not sure if I'm doing something I shouldn't be doing, but whenever I import a pipe in my component the AppShellPlugin fails. Is anybody experiencing this as well?

Component File:

```
import { Component } from '@angular/core';

import { DomainNamePipe } from '../pipes/domain-name.pipe.ts';

@Component({
  moduleId: module.id,
  selector: 'app-main-content',
  template: `
    // template markup
   `,
  pipes: [DomainNamePipe],
  styles:[]
})
```

Pipe:

```
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'domainName'
})

export class DomainNamePipe implements PipeTransform {
  transform(value: any, args?: any): any {
    return 'test';
  }
}
```

Error:

```
The Broccoli Plugin: [AppShellPlugin] failed with:
undefined

The broccoli plugin was instantiated at: 
    at AppShellPlugin.Plugin (/home/houssein/Dev/angular/angular2-hn/node_modules/broccoli-plugin/index.js:10:31)
    at AppShellPlugin.CachingWriter [as constructor] (/home/houssein/Dev/angular/angular2-hn/node_modules/broccoli-caching-writer/index.js:18:10)
    at new AppShellPlugin (/home/houssein/Dev/angular/angular2-hn/node_modules/angular2-broccoli-prerender/dist/prerender.js:15:16)
    at Angular2App._buildTree (/home/houssein/Dev/angular/angular2-hn/node_modules/angular-cli/lib/broccoli/angular2-app.js:161:48)
    at new Angular2App (/home/houssein/Dev/angular/angular2-hn/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/home/houssein/Dev/angular/angular2-hn/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/houssein/Dev/angular/angular2-hn/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/houssein/Dev/angular/angular2-hn/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/home/houssein/Dev/angular/angular2-hn/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/houssein/Dev/angular/angular2-hn/node_modules/angular-cli/node_modules/ember-cli/lib/tasks/serve.js:15:19)
    at /home/houssein/Dev/angular/angular2-hn/node_modules/angular-cli/node_modules/ember-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/home/houssein/Dev/angular/angular2-hn/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/houssein/Dev/angular/angular2-hn/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/houssein/Dev/angular/angular2-hn/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/houssein/Dev/angular/angular2-hn/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

**Comment by hdjirdeh** [comment]
This was a long time ago (a lot has changed) -- closing
