### ISSUE TITLE
`Cannot read property 'makeCurrent' of undefined` on ng serve

### ISSUE THREAD

**Issue by refrigerator** [angular/mobile-toolkit#89]
I've just installed the sample `hello-mobile` app but when I run `ng serve` I get this:

`Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Cannot read property 'makeCurrent' of undefined

TypeError: Cannot read property 'makeCurrent' of undefined
    at Object.<anonymous> (/Users/Taimur/workspace/hello-mobile/node_modules/angular2-universal/dist/node/node.js:7:35)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Taimur/workspace/hello-mobile/node_modules/angular2-universal/dist/node/index.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Taimur/workspace/hello-mobile/node_modules/angular2-broccoli-prerender/dist/prerender.js:8:28)
    at Module._compile (module.js:409:26)`

any ideas?

**Comment by refrigerator** [comment]
Closing - http://stackoverflow.com/questions/38195887/cannot-read-property-makecurrent-of-undefined-in-angular-mobile fixed it (had to update npm too)
